name: strava
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - pandoc
  - python=3.7
  - jq
  - libv8
  - r-cowplot
  - r-devtools
  - r-dplyr
  - r-forcats
  - r-ggmap
  - r-ggplot2
  - r-glue
  - r-here
  - r-httr
  - r-knitr
  - r-lubridate
  - r-magrittr
  - r-rmarkdown
  - r-readr
  - r-scales
  - r-tidyr
  - snakemake=5.5.0

