name: auto-update

on:
  schedule:
    - cron: '0 5 * * *'

jobs:
  update:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
           activate-environment: strava
           environment-file: environment.yml
           python-version: 3.7
           auto-activate-base: false
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: sliteteam/github-action-git-crypt-unlock@1.0.2
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      - name: Update
        shell: bash -l {0}
        run: |
          snakemake
          git add .
          git config --local user.email "noreply@github.com"
          git config --local user.name "GitHub"
          git diff-index --quiet HEAD \
          || git commit \
          --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" \
          -m '🤖 Auto-update'
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
