on:
  push:
    branches:
    - 'master'
  pull_request:
    branches:
    - 'master'

jobs:
  build:
    runs-on: 'macos-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
           activate-environment: strava
           environment-file: config/environment.yml
           python-version: 3.6
           auto-activate-base: false
      - name: snakemake
        shell: bash -l {0}
        run: |
          snakemake
          git status
          git add .
          git config --local user.email "noreply@github.com"
          git config --local user.name "GitHub"
          git diff-index --quiet HEAD \
          || git commit \
          --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" \
          -m '📊 Auto-update'
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}